config/routes.rb
Rails.application.routes.draw do
  

  get 'pages/about'

  get 'yourposts/index'

  resources :articles do
    resources :comments
    
    get 'upvote/create'

  get 'upvote/destroy'
  end
  resources :users
  resources :latestposts
get '/about', to: 'pages#about'
get '/yourpost', to: 'yourposts#index'
  get "/log-in" => "sessions#new"
post "/log-in" => "sessions#create"
get "/log-out" => "sessions#destroy", as: :log_out

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :upvotes, dependent: :destroy

  def score
    upvotes.count
  end
   def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%") 
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	#one-to-one relationship with profiles table
	belongs_to :user
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
    
  validates_uniqueness_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :password
validates_presence_of :password
validates_presence_of :email


validates_confirmation_of :password
before_save :encrypt_password


has_many :articles, dependent: :destroy

has_many :upvotes, :through => :articles
has_many :comments, :through => :articles

def encrypt_password
  self.password_salt = BCrypt::Engine.generate_salt
  self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
end



def self.authenticate(email, password)
user = User.where(email: email).first
if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
user
else
nil
end
end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController


	def index
		@comments =Comment.find(params[:id]).joins(:user) 
		
	end
	def create

    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(params[:comment].permit(:name, :body))
 @comment.user_id = current_user.id
     @comment.save
     
    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:article_id])
    @comment = @article.comments.find(params[:id])
    @comment.destroy
 
    redirect_to article_path(@article)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/upvote_controller.rb
class UpvoteController < ApplicationController
def create
    @article = Article.find(params[:article_id])
    if @article.upvotes.count == 0
    @upvote = @article.upvotes.create(params[:upvote])
     @upvote.user_id = current_user.id
     @upvote.save
    redirect_to article_path(@article)


else
redirect_to article_path(@article), notice: 'you have already liked.' 
end

  end
  def destroy
  	@article = Article.find(params[:article_id])
  	if @article.upvotes.count > 0
  		
  	
    
    @upvote = @article.upvotes.find_by(params[:user_id])

    @upvote.destroy
 
    redirect_to article_path(@article)
else
	redirect_to article_path(@article), notice: 'you have already unliked.' 
end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def create
@user = User.new(user_params)
if @user.save
flash[:notice] = "Welcome to the site!"
redirect_to "/"
else
flash[:alert] = "There was a problem creating your account. Please try again."
redirect_to :back
end
end
private
def user_params
params.require(:user).permit(:email, :password, :password_confirmation, :firstname, :lastname)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/latestposts_helper.rb
module LatestpostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/popularposts_helper.rb
module PopularpostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/upvote_helper.rb
module UpvoteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/yourposts_helper.rb
module YourpostsHelper
end

app/views/comments/_comment.html.erb
<div class="well">
<div class="comment clearfix">
  <div class="comment_content">

       
    <p class="comment_body"><%= comment.body %></p>
    <p class="comment_time"><%= time_ago_in_words(comment.created_at) %> Ago| By <% if comment.user.nil? %>
  
   <% else %>
    <%= comment.user.email%>

  <% end %></p>
  </div>

  <% if current_user.id == @article.user_id %> 
  <p><%= link_to 'Delete', [comment.article, comment], 
                  method: :delete, 
                  class: "button", 
                  data: { confirm: 'Are you sure?' } %></p> 
<% end %>
</div>


</div>

app/views/comments/_form.html.erb
<%if current_user%>

<div class= "well">
<%= form_for([@article, @article.comments.build]) do |f| %>
  <br>
  <%= f.text_area :body, rows:"6", cols: "75", placeholder: "Comments!"%><br>
  <br>
  <%=f.submit "Your Comment", class: "btn btn-md btn-primary  signup-btn" %>
<% end %>
</div>


<%else%>


<h5>Please Login first<h5>
<%= render 'sessions/form' %>










<%end%>

app/views/comments/edit.html.erb
<h1>Editing Comment</h1>

<%= render 'form' %>

<%= link_to 'Show', @comment %> |
<%= link_to 'Back', comments_path %>

app/views/comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Comments</h1>

<table>
  <thead>
    <tr>
      <th>Article</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td><%= comment.article_id %></td>
        <td><%= comment.body %></td>
        <td><%= link_to 'Show', comment %></td>
        <td><%= link_to 'Edit', edit_comment_path(comment) %></td>
        <td><%= link_to 'Destroy', comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comment', new_comment_path %>

app/views/comments/new.html.erb
<h1>New Comment</h1>

<%= render 'form' %>

<%= link_to 'Back', comments_path %>

app/views/comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Article:</strong>
  <%= @comment.article_id %>
</p>

<p>
  <strong>Body:</strong>
  <%= @comment.body %>
</p>

<%= link_to 'Edit', edit_comment_path(@comment) %> |
<%= link_to 'Back', comments_path %>