config/routes.rb
Rails.application.routes.draw do
  

  get 'pages/about'

  get 'yourposts/index'

  resources :articles do
    resources :comments
    
    get 'upvote/create'

  get 'upvote/destroy'
  end
  resources :users
  resources :latestposts
get '/about', to: 'pages#about'
get '/yourpost', to: 'yourposts#index'
  get "/log-in" => "sessions#new"
post "/log-in" => "sessions#create"
get "/log-out" => "sessions#destroy", as: :log_out

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :upvotes, dependent: :destroy

  def score
    upvotes.count
  end
   def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%") 
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	#one-to-one relationship with profiles table
	belongs_to :user
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
    
  validates_uniqueness_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :password
validates_presence_of :password
validates_presence_of :email


validates_confirmation_of :password
before_save :encrypt_password


has_many :articles, dependent: :destroy

has_many :upvotes, :through => :articles
has_many :comments, :through => :articles

def encrypt_password
  self.password_salt = BCrypt::Engine.generate_salt
  self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
end



def self.authenticate(email, password)
user = User.where(email: email).first
if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
user
else
nil
end
end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index



    if params[:search]
      @articles = Article.search(params[:search]).order("created_at DESC").joins(:user)
    else
      @articles = Article.all.order("created_at DESC").joins(:user)
    end

  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    if current_user
    @article = Article.new

  else
    redirect_to log_in_path, notice: 'Please in first' 
  end

  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create

    @article = current_user.articles.new(article_params)
       
    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/controllers/upvote_controller.rb
class UpvoteController < ApplicationController
def create
    @article = Article.find(params[:article_id])
    if @article.upvotes.count == 0
    @upvote = @article.upvotes.create(params[:upvote])
     @upvote.user_id = current_user.id
     @upvote.save
    redirect_to article_path(@article)


else
redirect_to article_path(@article), notice: 'you have already liked.' 
end

  end
  def destroy
  	@article = Article.find(params[:article_id])
  	if @article.upvotes.count > 0
  		
  	
    
    @upvote = @article.upvotes.find_by(params[:user_id])

    @upvote.destroy
 
    redirect_to article_path(@article)
else
	redirect_to article_path(@article), notice: 'you have already unliked.' 
end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
def create
@user = User.new(user_params)
if @user.save
flash[:notice] = "Welcome to the site!"
redirect_to "/"
else
flash[:alert] = "There was a problem creating your account. Please try again."
redirect_to :back
end
end
private
def user_params
params.require(:user).permit(:email, :password, :password_confirmation, :firstname, :lastname)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/latestposts_helper.rb
module LatestpostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/popularposts_helper.rb
module PopularpostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/upvote_helper.rb
module UpvoteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/yourposts_helper.rb
module YourpostsHelper
end

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <% if @article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% @article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body , class: "form-control" ,rows: "8"%>
  </div>
  <div class="actions">
    <%=f.submit "New Article", class: "btn btn-sm btn-primary  " %>
  </div>
<% end %>

app/views/articles/_latest.html.erb
    <%@latests = Article.all.order('created_at DESC').limit(3).joins(:user) %>

<% @latests.each do |latest| %>

                <div class="post-preview">
                    
                        <h6 class="post-title">
                            <%= link_to latest.title , latest %>
                            <hr>
                        </h6>
                     
                </div>
                

               

<%end%>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form' %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<div class="container">
     <div id="blog" class="row"> 
     <% @articles.each do |article| %>
                
                                   <div class="col-md-10 blogShort">
                     <h1><%= article.title%></h1>
                     <img src="http://www.kaczmarek-photo.com/wp-content/uploads/2012/06/guinnes-150x150.jpg" alt="post img" class="pull-left img-responsive thumb margin10 img-thumbnail">
                     
                         
                     <article><p>
                         <%= article.body.first(700) %>.....  
                         </p>

                        
                    </article>
                   <ul class="list-inline list-unstyled">
  			<li><span><i class="glyphicon glyphicon-calendar"></i> <%= article.created_at.strftime("%B %d, %Y") %>|Submitted <%= time_ago_in_words(article.created_at) %> Ago </span></li>
            <li>|</li>
            <span><i class="glyphicon glyphicon-comment"></i><%= article.comments.count%> Comments</span>
            <li>|</li>
            <li>
                 Posted by <%=article.user.firstname%>
            </li>
            <li>|</li>
            <li>
            <!-- Use Font Awesome http://fortawesome.github.io/Font-Awesome/ -->
              <span><i class="fa fa-facebook-square"></i></span>
              <span><i class="fa fa-twitter-square"></i></span>
              <span><i class="fa fa-google-plus-square"></i></span>
            </li>
			</ul>







                    <%= link_to 'Read More....' , article, class: "btn btn-blog pull-right marginBottom10"%> 
                    
                 </div>
                 <%end%>
                  </div>
</div>



<style>
 .blogShort{ border-bottom:1px solid #ddd;}
.add{background: #333; padding: 10%; height: 300px;}



/*.btn-blog {
    color: #ffffff;
    background-color: #37d980;
    border-color: #37d980;
    border-radius:0;
    margin-bottom:10px
}*/
.btn-blog:hover,
.btn-blog:focus,
.btn-blog:active,
.btn-blog.active,
.open .dropdown-toggle.btn-blog {
    color: white;
    background-color:#0099FF;
    border-color: #0099FF;
}
 h2{color:#34ca78;}
 .margin10{margin-bottom:10px; margin-right:10px;}
</style>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form' %>

<%= button_to 'Back', articles_path, class: "btn btn-lg btn-primary" ,:method => :get %>

app/views/articles/show.html.erb
<%= link_to "Like", article_upvote_create_path(@article), class: "navbar-brand" , :method => :get  %>|<%= link_to "Unlike", article_upvote_destroy_path(@article), class: "navbar-brand", :method => :get  %>

<div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
               
  <strong>Title:</strong>
  <%= @article.title %>
  <p class="post-meta">Posted by <%=@article.user.email%> on <%= @article.created_at.strftime("%B %d, %Y") %>|
<%if current_user%>
                    <%if current_user.id == @article.user.id%>
                        <%= link_to 'Edit', edit_article_path(@article) %>|
                        <%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %>


                        <%end%>
                        <%end%>

  </p>

<hr />

<div class="well">
  
  <%= @article.body %>
  </div>
  <div id="comments">

    <h2><%= @article.comments.count %> Comments</h2>
    <%= render @article.comments %>
 
    <h3>Add a comment:</h3>
    <%= render "comments/form" %>
  </div>





                    
                </div>
            </div>

app/views/upvote/_form.html.erb
<%= form_for @post.upvotes.build , remote: true do  |f| %>
  <%= f.hidden_field :user, value: current_user %>
  <%= f.submit 'Upvote', class: 'upvote-submit' %>
<% end %>

app/views/upvote/create.html.erb
<h1>Upvote#create</h1>
<p>Find me in app/views/upvote/create.html.erb</p>

app/views/upvote/destroy.html.erb
<h1>Upvote#destroy</h1>
<p>Find me in app/views/upvote/destroy.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Users</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<br />
<br />
<br />	
<br />
<br />
<%=form_for User.new, html: {class: 'form'} do |f| %>
  <div class="container" id="wrap">
	  <div class="row">
        <div class="col-md-6 col-md-offset-3">
            
                  <h4>It's free and always will be.</h4>
                    <div class="row">
                        <div class="col-xs-6 col-md-6">
                           <%=f.text_field :firstname, class: "form-control input-lg", placeholder: "First Name"%>
                                 
                        </div>
                        <div class="col-xs-6 col-md-6">
                            <%=f.text_field :lastname, class: "form-control input-lg", placeholder: "Last Name" %>
                        </div>
                    </div>
                      <%=f.text_field :email, class: "form-control input-lg", placeholder: " Enter Your Email" %>
                      <%=f.password_field :password, class: "form-control input-lg", placeholder: "Password" %>
                     <%=f.password_field :password_confirmation, class: "form-control input-lg", placeholder: "Comfirm Password" %>
        </div>
                     
            <br />
           
                       <%=f.submit "Create My Account", class: "btn btn-lg btn-primary btn-block signup-btn" %>
                   
     </div>

              
              
  </div>            


<%end%>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>