config/routes.rb
Rails.application.routes.draw do
  

  get 'pages/about'

  get 'yourposts/index'

  resources :articles do
    resources :comments
    
    get 'upvote/create'

  get 'upvote/destroy'
  end
  resources :users
  resources :latestposts
get '/about', to: 'pages#about'
get '/yourpost', to: 'yourposts#index'
  get "/log-in" => "sessions#new"
post "/log-in" => "sessions#create"
get "/log-out" => "sessions#destroy", as: :log_out

  root 'articles#index'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :user
	has_many :comments, dependent: :destroy
	has_many :upvotes, dependent: :destroy

  def score
    upvotes.count
  end
   def self.search(query)
    # where(:title, query) -> This would return an exact match of the query
    where("title like ?", "%#{query}%") 
  end
  
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :articles
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
end

app/models/like.rb
class Like < ActiveRecord::Base
end

app/models/profile.rb
class Profile < ActiveRecord::Base
	#one-to-one relationship with profiles table
	belongs_to :user
end

app/models/upvote.rb
class Upvote < ActiveRecord::Base
  belongs_to :article
  belongs_to :user
    
  validates_uniqueness_of :user_id
end

app/models/user.rb
class User < ActiveRecord::Base
attr_accessor :password
validates_presence_of :password
validates_presence_of :email


validates_confirmation_of :password
before_save :encrypt_password


has_many :articles, dependent: :destroy

has_many :upvotes, :through => :articles
has_many :comments, :through => :articles

def encrypt_password
  self.password_salt = BCrypt::Engine.generate_salt
  self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
end



def self.authenticate(email, password)
user = User.where(email: email).first
if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
user
else
nil
end
end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/latestposts_helper.rb
module LatestpostsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/popularposts_helper.rb
module PopularpostsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/upvote_helper.rb
module UpvoteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/yourposts_helper.rb
module YourpostsHelper
end

app/views/navigation/_nav.html.erb
<nav class="navbar navbar-default " role="navigation">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      
      <%= link_to "Rails Blog", "/" ,class: "navbar-brand" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      <li><%= link_to "New Post", new_article_path, :method => :get  %> </li>
        <li class="active">
        	  <% if current_page?(root_path) %>
    <h4>All Posts</h4>
  <% elsif current_page?(about_path) %>
    About
  <% else %>
    <%= link_to "Back to All Posts", root_path %>
  <% end %>

        </li>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">Latest posts <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="drop"><%= render "latestposts/latest" %></li>
          </ul>
        </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">popular posts <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li class="drop"><%= render "popularposts/popular" %></li>
            
          </ul>
        </li>
        <li><%= link_to "About", about_path %></li>
      </ul>













      <%= form_tag(articles_path, :method => "get", class: "navbar-form navbar-left", id: "search-form") do %>
    <div class="form-group">
      <%= text_field_tag :search, params[:search], class: "form-control", placeholder: "Search" %>
      <!-- In order to have the "search" icon int the button, we need to use plain HTML instead 
           of using a Rails form helper -->
           </div>
      <button class="btn btn-default" type="submit"><i class="icon-search"></i>Submit</button>
    
  <% end %>
      <ul class="nav navbar-nav navbar-right">
      <%if !current_user%>
        <li><p class="navbar-text">Already have an account?</p>
        <%else%>
        <p class="navbar-text"><%= current_user.email %></p>.
       <% end %>
       </li>


        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
         <% if current_user %>
         <b>Your Details</b>
         <% else %>
          <b>Login</b>
         <% end %>
           <span class="caret"></span></a>
			<ul id="login-dp" class="dropdown-menu">
			<% if current_user %>
              <li class="navbar-text "> Logged in as <strong><%= current_user.email %></strong>.</li>
              <li><%= link_to "Logout", log_out_path, method: :get, :class => 'navbar-link'  %></li>
              <% else %>

				<li>
					 <div class="row">
							<div class="col-md-12">

								<%= render 'sessions/form' %>
								
								 
							</div>
							<div class="bottom text-center">
								New here ? <li><%= link_to "Join us", new_user_path, :class => 'navbar-link'  %> &nbsp;</li>
							</div>
					 </div>
				</li>
				<% end %>
			</ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>










<style>
/*body{
    background:url('http://www.wallpaperup.com/uploads/wallpapers/2012/10/21/20181/cad2441dd3252cf53f12154412286ba0.jpg');
    
}*/
.drop{
  min-width: 250px;
  padding: 14px 14px 0;
}
#login-dp{
    min-width: 250px;
    padding: 14px 14px 0;
    overflow:hidden;
    background-color:rgba(255,255,255,.8);
}
#login-dp .help-block{
    font-size:12px    
}
#login-dp .bottom{
    background-color:rgba(255,255,255,.8);
    border-top:1px solid #ddd;
    clear:both;
    padding:14px;
}
#login-dp .social-buttons{
    margin:12px 0    
}
#login-dp .social-buttons a{
    width: 49%;
}
#login-dp .form-group {
    margin-bottom: 10px;
}
.btn-fb{
    color: #fff;
    background-color:#3b5998;
}
.btn-fb:hover{
    color: #fff;
    background-color:#496ebc 
}
.btn-tw{
    color: #fff;
    background-color:#55acee;
}
.btn-tw:hover{
    color: #fff;
    background-color:#59b5fa;
}
@media(max-width:768px){
    #login-dp{
        background-color: inherit;
        color: #fff;
    }
    #login-dp .bottom{
        background-color: inherit;
        border-top:0 none;
    }
}

</style>

app/views/sidebar/_sidebar.html.erb
<div class="panel-group" id="accordion">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne"><span class="glyphicon glyphicon-list-alt">
                            </span>Latest Posts</a>
                        </h4>
                    </div>
                    <div id="collapseOne" class="panel-collapse collapse in">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <span class="glyphicon glyphicon-pencil text-primary"></span><%= render "latestposts/latest" %>
                                    </td>
                                </tr>
                                
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo"><span class="glyphicon glyphicon-th">
                            </span>Popular posts</a>
                        </h4>
                    </div>
                    <div id="collapseTwo" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                        <%= render "popularposts/popular" %> 
                                    </td>
                                </tr>
                                
                            </table>
                        </div>
                    </div>
                </div>
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4 class="panel-title">
                            <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree"><span class="glyphicon glyphicon-user">
                            </span>Your Posts</a>
                        </h4>
                    </div>
                    <div id="collapseThree" class="panel-collapse collapse">
                        <div class="panel-body">
                            <table class="table">
                                <tr>
                                    <td>
                                     <%= bootstrap_flash %>
          <% if current_page?('/yourpost') %>
          <%= yield %>
          <%else%>
           <p>Please login first</p>
          <%end%>
                                    </td>
                                </tr>
                                
                            </table>
                        </div>
                    </div>
                </div>  
            </div>